export const categoryConstant = {
  GET_ALL_CATEGORIES_REQUEST: "GET_ALL_CATEGORIES_REQUEST",
  GET_ALL_CATEGORIES_SUCCESS: "GET_ALL_CATEGORIES_SUCCESS",
  GET_ALL_CATEGORIES_FAILUER: "GET_ALL_CATEGORIES_FAILUER",
  ADD_NEW_CATEGORY_REQUEST: "ADD_NEW_CATEGORY_REQUEST",
  ADD_NEW_CATEGORY_SUCCESS: "ADD_NEW_CATEGORY_SUCCESS",
  ADD_NEW_CATEGORY_FAILUER: "ADD_NEW_CATEGORY_FAILUER",
};

export const productConstant = {
  GET_PRODUCTS_BY_SLUG: "GET_PRODUCTS_BY_SLUG",
};
